sources:
  cp-schema-registry:
    kind: dockerimage
    spec:
      image: devopsiaci/cp-schema-registry
      architecture: linux/amd64
      versionfilter:
        kind: semver
conditions: {}
targets:
  cp-schema-registry-helm:
    name: bump cp-schema-registry helm chart
    kind: helmchart
    spec:
      name: charts/cp-schema-registry
      file: Chart.yaml
      key: $.appVersion
      versionincrement: none
    sourceid: cp-schema-registry
